[noobi/week3] 3주차 실습&과제 디자인
SSUMC-7th/iOS_B pull request #12
Opened 2024-10-07 13:06 UTC by Funital

# iOS Pull Request

## 주차별 학습내용 기록

> 작성자가 편한대로 주차별 학습한 내용을 기록해주세요

- 내용
- UITableView가 무엇인지와 어떻게 적용하는지 알았다.
- Data를 전달하는 3가지 방법에 대해 알게되었다.
- UserDefault에 대해 알게 되었다.
- UserDefault와 TableView의 실습을 진행하면서 어떻게 쓰이는지 알게되었다.

## 궁금한 점 & 스터디원들과 의논해보고 싶은 점

> 스터디 간 궁금한 점들에 대해서 작성해주세요.
> 파트장의 도움이 필요할 때는 디스코드 `iOS 질문 채널`을 이용해주세요.

- 내용

## 체크리스트

- [ ] 주차별 스터디 라벨을 할당했습니까?
- [ ] 충돌문제를 해결했습니까?
- [ ] PR 병합 방향을 확인했습니까? 작성자 본인의 `main` 브랜치로 병합하는 것을 확인했습니까?

## 시연 영상

> 시연 영상을 첨부해주세요!

2024-10-08 02:11 UTC, jayn2u commented
시연영상이랑 체크리스트 꼭 해주세요!

2024-10-08 02:11 UTC, jayn2u requested changes
시연영상이랑 체크리스트 해주세요!

2024-10-08 10:41 UTC, jayn2u approved these changes

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/Cells/SavedCell.swift
> +    }
XIB 파일을 사용하지 않아서 필요없는 코드입니다!

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/Cells/SavedCell.swift
> +    }()
프로퍼티는 클래스 상단에 위치하는 게 좋아요!

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/Cells/SavedCell.swift
> +    }
Public 접근제한자를 사용해서 메소드를 정의한 이유가 뭘까요?

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/Models/LoginModel.swift
> +    }
Swift 마크업 주석을 사용해서 문서화를 하려고 했던 것 같아요.

이 때는 슬래시 3개를 사용해주시면 됩니다!

```swift
/// 유저가 입력한 id 값을 UserDefaults에 저장.
/// - Parameter id: 유저가 입력한 텍스트 값
public func saveUserId(_ id: String) {
        userId.set(id, forKey: userIdKey)
}
```

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/ViewControllers/LoginViewController.swift
> +        ])
`SnapKit`을 배웠으니, `SnapKit`을 앞으로 활용하는 것을 추천해요!

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/ViewControllers/LoginViewController.swift
> +        loginModel.saveUserPwd(password)
이렇게 `Model` 객체를 사용하는 코드가 정말 훌륭합니다.
"관심사를 분리한다"라고 하는데, 아키텍처를 기반으로 의존성을 분리해서 동작하는 코드를 설계할 수 있어요!

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/ViewControllers/MyViewController.swift
> +    var profileImage: UIImage?
옵셔널로 프로퍼티를 선언하면, 얻을 수 있는 이점에는 무엇이 있을까요? 퀴즈입니당. :)

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/ViewControllers/ProfileManageViewController.swift
> +    var isPasswordEditing = false
이렇게 주석을 남겨서 프로퍼티들을 명세하는 습관도 정말 좋아요!

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/ViewControllers/ProfileManageViewController.swift
> +        }
`if let`을 사용하는 것을 **옵셔널 바인딩**이라고 해요!
`guard let`을 사용하는 방법도 있답니다.

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/ViewControllers/ProfileManageViewController.swift
> +        if isEmailEditing {
변수 이름을 정말 잘 지었습니다.

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/ViewControllers/SavedViewController.swift
> +}
`UITableViewDataSource`와 `UITableDelegate`를 분리하는 방법도 좋다고 생각해요.
이건 개발자마다 스타일 차이겠지만, 저는 분리한답니다!

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/Views/MyView.swift
> +    let cameraButton = UIButton()
클로저를 사용해서, 프로퍼티 선언을 하지 않았네요?!

2024-10-08 10:41 UTC, jayn2u commented on noobi/week3/Kream/Kream/Views/SavedView.swift
> +        }
`$0`으로 많이 하긴 하지만 다음과 같이 클로저에 파라미터를 직접 작성할 수도 있어요!

```swift
title.snp.makeConstraints { make in
            make.top.equalToSuperview().offset(50)
            make.left.equalToSuperview().offset(20)
            make.right.equalToSuperview().offset(-183)
}
```

2024-10-11 08:34 UTC, Hrepay approved these changes
승인합니다.

2024-10-11 08:34 UTC, dlwnsgurz reviewed
승인합니다.

2024-10-11 08:35 UTC, merged